name: snake
description: Dreaming snake

version: 1.0.1+101

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scoped: ^0.4.0
  audioplayers: ^0.7.8
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"

flutter:
  uses-material-design: true
  assets:
    - assets/music/bensound_instinct.mp3
  #  - images/a_dot_ham.jpeg

  fonts:
    - family: FFF Forward
      fonts:
        - asset: assets/fonts/fffforward.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/snake_icon.png"
